org: joshdann40
app: my-app
service: my-service

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
          Resource: "*"

functions:
  hello:
    handler: handlers/handler.hello
    events:
      - httpApi:
          path: /
          method: get

  health:
    handler: handlers/handler.health
    events:
      - httpApi:
          path: /health
          method: get

  users:
    handler: handlers/handler.users
    events:
      - httpApi:
          path: /users
          method: get

  createUser:
    handler: handlers/handler.createUser
    events:
      - httpApi:
          path: /users
          method: post

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
