- name: Debug Step
  run: echo "Pipeline running"

- name: Check AWS Key Length
  run: |
    echo "Access Key Length:"
    echo ${#AWS_ACCESS_KEY_ID}

- name: Configure AWS Credentials
  uses: aws-actions/configure-aws-credentials@v4
  with:
    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    aws-region: ap-south-1
